[[main]]
  identifier = "blogy"
  name = "Blogy"
  url = "blogy"
  weight = 10

[[main]]
  identifier = "faq"
  name = "Faq"
  url = "faq"
  weight = 9

[[main]]
  identifier = "ONas"
  name = "O Nas"
  url = "onas"
  weight = 8
